spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    schemas:
      - public
    baseline-on-migrate: true
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs

logging:
  level:
    sql: info
    org.springframework.security: DEBUG
jwt:
  secret: 8dc3e0e6fe23d1c4be967fbf11c960ea70189b42e1f0b15723e1a68a2c142b6bw4eTsDqZh6J8dc3e0e6fe23d1cb6bw4eTsDqZh6J